# Generated by Django 4.2.13 on 2025-11-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CupoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('group_code', models.CharField(blank=True, default='', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=16)),
            ],
            options={
                'db_table': 'requests_cupo',
            },
        ),
    ]
