# Generated by Django 4.2 on 2025-11-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('term', models.CharField(max_length=20)),
                ('group_code', models.CharField(max_length=10)),
                ('teacher_id', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups_group',
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lun'), ('TUE', 'Mar'), ('WED', 'Mié'), ('THU', 'Jue'), ('FRI', 'Vie'), ('SAT', 'Sáb'), ('SUN', 'Dom')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='groups.group')),
            ],
            options={
                'db_table': 'groups_schedule',
            },
        ),
    ]
